// src/components/aizen/AizenChatMessage.tsx
"use client";

import { Card, CardContent } from "@/components/ui/card";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import Image from "next/image";
import ReactMarkdown from 'react-markdown';
import { Copy, ThumbsUp, ThumbsDown } from 'lucide-react';
import { useToast } from "@/hooks/use-toast";
import { useState } from "react";

export type Message = {
  id: string;
  sender: 'user' | 'aizen';
  text: string;
  timestamp?: Date;
  isLoadingPlaceholder?: boolean;
  imageUrl?: string; // For generated images
  imagePrompt?: string; // Optional: prompt used for the image
  feedback?: 'liked' | 'disliked' | null; // For user feedback
};

interface AizenChatMessageProps {
  message: Message;
  onUpdateMessage?: (messageId: string, updates: Partial<Message>) => void; // For feedback
}

export function AizenChatMessage({ message, onUpdateMessage }: AizenChatMessageProps) {
  const isAizen = message.sender === 'aizen';
  const { toast } = useToast();
  const [feedbackState, setFeedbackState] = useState(message.feedback);


  const handleCopy = () => {
    navigator.clipboard.writeText(message.text)
      .then(() => {
        toast({ title: "Copied to clipboard!", description: "Aizen's words are now yours." });
      })
      .catch(err => {
        toast({ title: "Copy Failed", description: "Could not copy message.", variant: "destructive" });
        console.error('Failed to copy text: ', err);
      });
  };

  const handleFeedback = (newFeedback: 'liked' | 'disliked') => {
    const updatedFeedback = feedbackState === newFeedback ? null : newFeedback;
    setFeedbackState(updatedFeedback);
    if (onUpdateMessage) {
      onUpdateMessage(message.id, { feedback: updatedFeedback });
    }
    // In a real app, you might send this feedback to a server
    console.log(`Feedback for message ${message.id}: ${updatedFeedback}`);
  };


  if (message.isLoadingPlaceholder && isAizen) {
    return (
      <div className={cn("flex items-end gap-2 mb-4 justify-start")}>
        <Avatar className="w-10 h-10 self-start">
          <AvatarImage src="https://placehold.co/100x100/000000/FFFFFF.png?text=A" alt="Aizen" data-ai-hint="samurai mask"/>
          <AvatarFallback>A</AvatarFallback>
        </Avatar>
        <Card 
          className={cn(
            "max-w-[70%] p-0 shadow-lg bg-secondary/80 rounded-tr-xl rounded-bl-xl rounded-br-xl border-border/50 animate-pulse"
          )}
        >
          <CardContent className="p-3">
            <p className="whitespace-pre-wrap text-sm leading-relaxed italic">{message.text}</p>
          </CardContent>
        </Card>
      </div>
    );
  }


  return (
    <div className={cn("flex items-end gap-2 mb-4", isAizen ? "justify-start" : "justify-end")}>
      {isAizen && (
        <Avatar className="w-10 h-10 self-start shrink-0">
          <AvatarImage src="https://placehold.co/100x100/000000/FFFFFF.png?text=A" alt="Aizen" data-ai-hint="samurai mask"/>
          <AvatarFallback>A</AvatarFallback>
        </Avatar>
      )}
      <Card 
        className={cn(
          "max-w-[70%] p-0 shadow-lg group relative", // Added group relative for buttons
          isAizen ? "bg-secondary/80 rounded-tr-xl rounded-bl-xl rounded-br-xl" : "bg-primary/80 text-primary-foreground rounded-tl-xl rounded-br-xl rounded-bl-xl",
          "border-border/50"
        )}
      >
        <CardContent className="p-3">
          {isAizen ? (
            <ReactMarkdown
              className="prose prose-sm prose-invert max-w-none break-words"
              components={{
                // Customize Markdown rendering if needed
                p: ({node, ...props}) => <p className="mb-2 last:mb-0" {...props} />,
                ul: ({node, ...props}) => <ul className="list-disc list-inside mb-2" {...props} />,
                ol: ({node, ...props}) => <ol className="list-decimal list-inside mb-2" {...props} />,
                code: ({node, inline, ...props}) => 
                  inline ? <code className="bg-muted/50 px-1 py-0.5 rounded-sm text-xs" {...props} /> : <pre className="bg-muted/50 p-2 rounded-md overflow-x-auto text-xs my-2" {...props} />,
              }}
            >
              {message.text}
            </ReactMarkdown>
          ) : (
            <p className="whitespace-pre-wrap text-sm leading-relaxed">{message.text}</p>
          )}

          {message.imageUrl && (
            <div className="mt-3 rounded-lg overflow-hidden border border-border/30 shadow-inner">
              <Image 
                src={message.imageUrl} 
                alt={message.imagePrompt || "Generated by Aizen"} 
                width={300} 
                height={300} 
                className="object-contain w-full h-auto"
                data-ai-hint="samurai art"
              />
            </div>
          )}

          {message.timestamp && (
            <p className={cn("text-xs mt-2 pt-1 border-t border-border/20", isAizen ? "text-muted-foreground text-right" : "text-primary-foreground/70 text-right")}>
              {message.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
            </p>
          )}
        </CardContent>
        {isAizen && !message.isLoadingPlaceholder && (
          <div className="absolute -top-2 -right-2 opacity-0 group-hover:opacity-100 transition-opacity flex gap-1 p-1 bg-card/70 backdrop-blur-sm rounded-md border border-border/30 shadow-md">
            <Button variant="ghost" size="icon" className="h-6 w-6 text-muted-foreground hover:text-foreground" onClick={handleCopy} title="Copy message">
              <Copy size={14} />
            </Button>
            <Button 
              variant="ghost" 
              size="icon" 
              className={cn("h-6 w-6 hover:text-green-500", feedbackState === 'liked' ? "text-green-500" : "text-muted-foreground")} 
              onClick={() => handleFeedback('liked')}
              title="Like response"
            >
              <ThumbsUp size={14} />
            </Button>
            <Button 
              variant="ghost" 
              size="icon" 
              className={cn("h-6 w-6 hover:text-red-500", feedbackState === 'disliked' ? "text-red-500" : "text-muted-foreground")} 
              onClick={() => handleFeedback('disliked')}
              title="Dislike response"
            >
              <ThumbsDown size={14} />
            </Button>
          </div>
        )}
      </Card>
       {!isAizen && (
        <Avatar className="w-10 h-10 self-start shrink-0">
           <AvatarImage src="https://placehold.co/100x100/FFFFFF/000000.png?text=U" alt="User" data-ai-hint="person silhouette"/>
          <AvatarFallback>U</AvatarFallback>
        </Avatar>
      )}
    </div>
  );
}
