
// src/components/aizen/ChatHistoryModal.tsx
"use client";

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
  DialogClose,
} from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Button } from "@/components/ui/button";
import type { Message } from "./AizenChatMessage";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { cn } from "@/lib/utils";

interface ChatHistoryModalProps {
  isOpen: boolean;
  onClose: () => void;
  messages: Message[];
}

export function ChatHistoryModal({ isOpen, onClose, messages }: ChatHistoryModalProps) {
  if (!isOpen) return null;

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-[600px] h-[80vh] flex flex-col bg-background/90 backdrop-blur-md border-border/50">
        <DialogHeader>
          <DialogTitle>Chat History</DialogTitle>
          <DialogDescription>
            Your current conversation with Aizen.
          </DialogDescription>
        </DialogHeader>
        <ScrollArea className="flex-grow my-4 pr-6"> {/* Added pr-6 for scrollbar spacing */}
          <div className="space-y-4">
            {messages.length > 0 ? (
              messages.map((msg) => (
                <div
                  key={msg.id}
                  className={cn(
                    "flex items-start gap-3",
                    msg.sender === "user" ? "justify-end" : "justify-start"
                  )}
                >
                  {msg.sender === "aizen" && (
                    <Avatar className="w-8 h-8 shrink-0">
                      <AvatarImage src="https://placehold.co/100x100/000000/FFFFFF.png?text=A" alt="Aizen" data-ai-hint="samurai mask"/>
                      <AvatarFallback>A</AvatarFallback>
                    </Avatar>
                  )}
                  <div
                    className={cn(
                      "max-w-[75%] rounded-lg px-3 py-2 text-sm shadow-sm",
                      msg.sender === "aizen"
                        ? "bg-secondary/80 text-secondary-foreground rounded-tr-lg rounded-bl-lg rounded-br-lg"
                        : "bg-primary/80 text-primary-foreground rounded-tl-lg rounded-br-lg rounded-bl-lg"
                    )}
                  >
                    <p className="whitespace-pre-wrap break-words">{msg.text}</p>
                    {msg.imageUrl && (
                         <div className="mt-2 rounded-md overflow-hidden border border-border/30">
                            <img 
                                src={msg.imageUrl} 
                                alt={msg.imagePrompt || "Generated by Aizen"} 
                                className="object-contain w-full h-auto max-h-48"
                                data-ai-hint="samurai art"
                            />
                        </div>
                    )}
                    {msg.timestamp && (
                      <p className={cn(
                        "text-xs mt-1 pt-1 border-t border-border/20 opacity-70", 
                        msg.sender === 'aizen' ? "text-right" : "text-right"
                        )}>
                        {new Date(msg.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                      </p>
                    )}
                  </div>
                  {msg.sender === "user" && (
                     <Avatar className="w-8 h-8 shrink-0">
                      <AvatarImage src="https://placehold.co/100x100/FFFFFF/000000.png?text=U" alt="User" data-ai-hint="person silhouette"/>
                      <AvatarFallback>U</AvatarFallback>
                    </Avatar>
                  )}
                </div>
              ))
            ) : (
              <p className="text-muted-foreground text-center">No messages in this session yet.</p>
            )}
          </div>
        </ScrollArea>
        <DialogFooter>
          <DialogClose asChild>
            <Button type="button" variant="outline">
              Close
            </Button>
          </DialogClose>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
